"use client";

import { useCallback, useEffect, useState } from "react";
import { MonthlyPerformanceChart, PipelineValueChart } from "@/components/charts/performance-chart";
import { ModulePageLayout } from "@/components/navigation/module-page-layout";
import { ErrorState } from "@/components/ui/error-state";
import { MetricCardSkeleton } from "@/components/ui/loading-skeleton";
import { MetricStatCard } from "@/components/ui/metric-card";
import { SectionTitle } from "@/components/ui/section-title";
import { getDashboardStats } from "@/lib/api";
import type { DashboardStatsResponse } from "@/lib/api-types";
import { monthlyPerformance } from "@/lib/demo-data";
import type { MetricCard } from "@/lib/types";

function buildMetrics(stats: DashboardStatsResponse): MetricCard[] {
  return [
    { label: "Total Contacts", value: stats.contacts.total.toLocaleString() },
    { label: "SMS Ready", value: stats.contacts.sms_ready.toLocaleString() },
    { label: "Needs Enrichment", value: stats.contacts.needs_enrichment.toLocaleString() },
    { label: "Do Not Contact", value: stats.contacts.do_not_contact.toLocaleString() },
  ];
}

function buildOutreachMetrics(stats: DashboardStatsResponse): MetricCard[] {
  return [
    { label: "SMS Sent", value: stats.outreach.sms_sent.toLocaleString() },
    { label: "SMS Reply Rate", value: `${(stats.outreach.sms_reply_rate * 100).toFixed(1)}%` },
    { label: "Emails Sent", value: stats.outreach.emails_sent.toLocaleString() },
    { label: "Meetings Booked", value: stats.outreach.meetings_booked.toLocaleString() },
  ];
}

export default function ReactivationDashboardPage() {
  const [stats, setStats] = useState<DashboardStatsResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(() => {
    setLoading(true);
    setError(null);
    getDashboardStats()
      .then(setStats)
      .catch((err) => setError(err.message))
      .finally(() => setLoading(false));
  }, []);

  useEffect(load, [load]);

  return (
    <ModulePageLayout
      moduleId="reactivation"
      title="Dead Lead Reactivation Dashboard"
      description="Monitor dormant pipeline recovery, sequence performance, and rep follow-through in one command center."
    >
      {error && <ErrorState message={error} onRetry={load} />}

      {loading ? (
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
          {Array.from({ length: 4 }).map((_, i) => (
            <MetricCardSkeleton key={i} />
          ))}
        </div>
      ) : stats ? (
        <>
          <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            {buildMetrics(stats).map((metric) => (
              <MetricStatCard key={metric.label} metric={metric} />
            ))}
          </div>

          <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            {buildOutreachMetrics(stats).map((metric) => (
              <MetricStatCard key={metric.label} metric={metric} />
            ))}
          </div>
        </>
      ) : null}

      <section className="rounded-xl border border-slate-800 bg-slate-900/70 p-5">
        <SectionTitle
          title="Reactivation Funnel"
          description="Six months of conversion from dormant contact to qualified opportunity."
        />
        <p className="mt-1 text-xs text-slate-500">Demo data</p>
        <div className="mt-4">
          <MonthlyPerformanceChart data={monthlyPerformance} />
        </div>
      </section>

      <section className="rounded-xl border border-slate-800 bg-slate-900/70 p-5">
        <SectionTitle
          title="Recovered Pipeline Trend"
          description="Monthly pipeline value generated by reactivation campaigns."
        />
        <p className="mt-1 text-xs text-slate-500">Demo data</p>
        <div className="mt-4">
          <PipelineValueChart data={monthlyPerformance} />
        </div>
      </section>
    </ModulePageLayout>
  );
}
