import { MonthlyPerformanceChart, PipelineValueChart } from "@/components/charts/performance-chart";
import { ModulePageLayout } from "@/components/navigation/module-page-layout";
import { MetricStatCard } from "@/components/ui/metric-card";
import { SectionTitle } from "@/components/ui/section-title";
import { monthlyPerformance, reactivationMetrics } from "@/lib/demo-data";

export default function ReactivationDashboardPage() {
  return (
    <ModulePageLayout
      moduleId="reactivation"
      title="Dead Lead Reactivation Dashboard"
      description="Monitor dormant pipeline recovery, sequence performance, and rep follow-through in one command center."
    >
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        {reactivationMetrics.map((metric) => (
          <MetricStatCard key={metric.label} metric={metric} />
        ))}
      </div>

      <section className="rounded-xl border border-slate-800 bg-slate-900/70 p-5">
        <SectionTitle
          title="Reactivation Funnel"
          description="Six months of conversion from dormant contact to qualified opportunity."
        />
        <div className="mt-4">
          <MonthlyPerformanceChart data={monthlyPerformance} />
        </div>
      </section>

      <section className="rounded-xl border border-slate-800 bg-slate-900/70 p-5">
        <SectionTitle
          title="Recovered Pipeline Trend"
          description="Monthly pipeline value generated by reactivation campaigns."
        />
        <div className="mt-4">
          <PipelineValueChart data={monthlyPerformance} />
        </div>
      </section>
    </ModulePageLayout>
  );
}
